### ISSUE TITLE
Integrate opcard application

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/nitrokey-3-firmware#100]
The [opcard](https://github.com/Nitrokey/opcard-rs) application provides an OpenPGP smart card.  This is a tracking issue for its integration into the Nitrokey 3 firmware.  For issues regarding the application itself, see the [opcard issue tracker](https://github.com/Nitrokey/opcard-rs/issues).

Current status:
- 2022-10-13: v0.1.0 alpha release ([app](https://github.com/Nitrokey/opcard-rs/releases/tag/v0.1.0), [firmware](https://github.com/Nitrokey/nitrokey-3-firmware/releases/tag/v1.2.2-alpha.opcard.0.1.0), only nrf52)
- 2022-11-18: v0.2.0 alpha release ([app](https://github.com/Nitrokey/opcard-rs/releases/tag/v0.2.0), [firmware](https://github.com/Nitrokey/nitrokey-3-firmware/releases/tag/v1.2.2-alpha.20221130))
- 2023-02-24: v0.3.0 alpha release ([app](https://github.com/Nitrokey/opcard-rs/releases/tag/v0.3.0), [firmware](https://github.com/Nitrokey/nitrokey-3-firmware/releases/tag/v1.2.2-alpha.20230224))
- 2023-04-13: v0.4.0 test release ([app](https://github.com/Nitrokey/opcard-rs/releases/tag/v0.4.0), [firmware](https://github.com/Nitrokey/nitrokey-3-firmware/releases/tag/v1.3.1-test.20230417))

To do:
- [ ] set manufacturer to `0x000F` (Nitrokey)
- [ ] set proper serial number

**Comment by robin-nitrokey** [comment]
[v1.2.2-alpha.20221130](https://github.com/Nitrokey/nitrokey-3-firmware/releases/tag/v1.2.2-alpha.20221130) released with [ocard v0.2.0](https://github.com/Nitrokey/opcard-rs/blob/main/CHANGELOG.md#020-2022-11-18).

**Comment by Hoeze** [comment]
Until when will OpenPGP be implemented?
My lab will soon buy some security tokens and I would prefer if we could get some open-source sticks instead of Yubikeys.

**Comment by szszszsz** [comment]
Hey @Hoeze !
We are testing it already in the test firmware, and plan to release it finally in the stable variant in the coming weeks. Target is beginning of May 2023.

Test firmware can be flashed and used by end-user right now, however it is not as much tested as the stable release.
See more about firmware variants at:
- https://github.com/Nitrokey/nitrokey-documentation/pull/146/files?short_path=aa99941#diff-aa999411574c41661c8f3edec54c08e150e804517e4bf010c416c405de676bcc

**Comment by Hoeze** [comment]
Thanks @szszszsz, this is great news!
We will evaluate possible options mid May, so this would be just in time :smile:
