### ISSUE TITLE
Embedded runner: nrf52840-hal is a git dependency without a `rev` set

### ISSUE THREAD

**Issue by sosthene-nitrokey** [Nitrokey/nitrokey-3-firmware#103]
This causes build issues when running `cargo update`

**Comment by robin-nitrokey** [comment]
I think that is fine as we are tracking the upstream main branch.  But it would be good to know why we use a Git dependency in the first place.  Given that is was added 9 months ago and the latest release was 29 days ago, we might be able to use a release instead.

**Comment by sosthene-nitrokey** [comment]
> latest release was 29 days ago

And this `nrf52840-hal` release (`0.12`) is incompatible with `nrf52840-pac` version `0.11` which is specified just under and depends on `nrf52840-hal` `0.11`.

**Comment by robin-nitrokey** [comment]
Did you check whether we can bump `nrf52840-pac`?

**Comment by sosthene-nitrokey** [comment]
I'm not sure, I think I tested and saw that id didn't compile and didn't try further.
