### ISSUE TITLE
Feature: Keep data on key after firmware update

### ISSUE THREAD

**Issue by xnuken** [Nitrokey/nitrokey-3-firmware#126]
Would be nice if its possible to keep the user data stored after a firmware update

**Comment by robin-nitrokey** [comment]
This should already be the case, except for the very first firmware update v1.0.1.  Did you lose any data during a firmware update?

**Comment by reinerh** [comment]
The documentation still warns that on updates all user data will get deleted: https://docs.nitrokey.com/de/nitrokey3/linux/firmware-update
Is this no longer the case? Because of this I didn't update the firmware on my NK3 yet, as I don't want to re-register it every time.
