### ISSUE TITLE
Gitlab/Codeberg etc code mirrors

### ISSUE THREAD

**Issue by phildev4** [Nitrokey/nitrokey-3-firmware#128]

**Comment by robin-nitrokey** [comment]
Could you add some context?  If it is just about having a backup, we already have that though it is not public.

**Comment by phildev4** [comment]
Mainly as a way for more privacy conscious individuals to access the source code without going to a Microsoft owned platform.  Not a necessity in any way but just a nice to have

**Comment by jornfranke** [comment]
fyi: It might be already archived on software heritage (https://www.softwareheritage.org/), but having an active mirror, such as Codeberg would be nice to have indeed
