### ISSUE TITLE
usbd-ccid:  panicked at 'assertion failed: packet.len() <= self.long_packet_missing'

### ISSUE THREAD

**Issue by sosthene-nitrokey** [Nitrokey/nitrokey-3-firmware#150]
This bug can be reached by running the example from https://github.com/Nitrokey/opcard-rs/pull/105 and running the `gnuk` test suite.

Panic location:

```
thread '<unnamed>' panicked at 'assertion failed: packet.len() <= self.long_packet_missing', /home/soso-nitrokey/.cache/cargo/git/checkouts/nitrokey-3-firmware-0614bf7d47ce1b5c/c02188a/components/usbd-ccid/src/pipe.rs:183:13
```

**Comment by sosthene-nitrokey** [comment]
The `gnuk` test suite hangs for around 1min40s (weird value), and it looks like after that the test suite times out and tries the next test, without any cleanup, so the error is probably somewhere else.

**Comment by sosthene-nitrokey** [comment]
I think I got it!

**Comment by szszszsz** [comment]
> 1min40s

100 seconds, perfectly round :-)
