### ISSUE TITLE
usbd-ccid: panicked at 'unexpectedly in receiving state'

### ISSUE THREAD

**Issue by sosthene-nitrokey** [Nitrokey/nitrokey-3-firmware#151]
This bug can be reached with the usbip runner from https://github.com/Nitrokey/nitrokey-3-firmware/pull/149 and running the gnuk test suite

Full panic:

```
thread 'main' panicked at 'unexpectedly in receiving state', /home/soso-nitrokey/.cache/cargo/git/checkouts/nitrokey-3-firmware-0614bf7d47ce1b5c/24d40b0/components/usbd-ccid/src/pipe.rs:323:22
```

**Comment by sosthene-nitrokey** [comment]
It looks like the device is receiving a new command even though it still hasn't fully sent the previous response. It only happens when the `highspeed-usb` feature is not enabled, which makes sense. USB 2.0 packets are always large enough to contain a full APDU.

**Comment by sosthene-nitrokey** [comment]
Ok, so it looks like it's actually a simple issue with the gnuk test suite. A test fails, the connection is not cleaned up, and the next test starts running.

**Comment by sosthene-nitrokey** [comment]
Ok no, this seems to come from us. When sending an apdu in multiple packets, usbd-ccid sends zlp (zero length packet) even after non-final packets.

If I understand correctly we should send a zlp only after the full apdu has been sent to mark the end of the transaction.

**Comment by robin-nitrokey** [comment]
I still get this when running `gpg --card-status` with the usbip-runner from main.  Does this work for you?

**Comment by sosthene-nitrokey** [comment]
I don't have it no.
