### ISSUE TITLE
NK3Mini: UP is not properly aborted

### ISSUE THREAD

**Issue by daringer** [Nitrokey/nitrokey-3-firmware#199]
It looks like once a User Presence request is started it can only time-out, but if an abort is requested it will not abort. A directly following 2nd UP request will lead to a "busy channel"

To reproduce, e.g. on Gitlab:
1. click "set up new device" 
2. (you see the device asking for UP) 
3.  click "cancel" in the browser 
4. the nk3mini still has the LED active 
5.  click "set up new device" again 
6.  confirm UP 
7.  nothing happens 
8.  "busy channel" (I suspect the device panics) 

aborting works good for the NK3AN (the LED stops and no busy channel)

**Comment by robin-nitrokey** [comment]
Interesting that it works with the NK3AN, cf. https://github.com/Nitrokey/nitrokey-3-firmware/issues/47.  Or is this something different?

**Comment by daringer** [comment]
I could also imagine that this is originating in the user presence hardware-specific-implementation, which actually makes the most sense if the behavior differs from the nk3an
