### ISSUE TITLE
NK3AN: U2F register request restart fails with panic

### ISSUE THREAD

**Issue by daringer** [Nitrokey/nitrokey-3-firmware#200]
Generally registering works, but if you restart the process as described below the NK3AN will panic...

Tested on gitlab + chromium (110):

1. click "set up new device" 
2. (device asking for UP) 
3.  click "USB-Security-Key" 
4.  click "try another way" 
5.  nk3an panics (red LED)

maybe partly related to #199 ?

**Comment by sosthene-nitrokey** [comment]
The panic was actually caused by `ctaphid-dispatch` not supporting cancelled requests, so once the UP returned (or timed out), the request was continuated and it failed to respond.

The panic is fixed in https://github.com/trussed-dev/ctaphid-dispatch/pull/2/files

**Comment by sosthene-nitrokey** [comment]
The fixed was included in #279
