### ISSUE TITLE
Set reasonable maximum numbers for persistent data

### ISSUE THREAD

**Issue by daringer** [Nitrokey/nitrokey-3-firmware#207]
In particular + my suggestions:

* maximum number of FIDO2 RKs (20)
* maximum number of secrets-app entries (100)

These are very conservative entries, which shall be higher in the future once we can promise better performance for e.g., secrets-app entries.

Best would be that these are passed as options into the app(s) instead of hard-coding them inside the apps - so later we can configure them through the `admin-app`

**Comment by robin-nitrokey** [comment]
Yes.  Currently, there is no limit, but we wanted to add one to make sure that the key does not become unusable due to the listing issue.

**Comment by robin-nitrokey** [comment]
Implemented for fido-authenticator in https://github.com/Nitrokey/fido-authenticator/pull/12 and https://github.com/Nitrokey/nitrokey-3-firmware/pull/239.
