### ISSUE TITLE
enable piv-authenticator for alpha releases

### ISSUE THREAD

**Issue by daringer** [Nitrokey/nitrokey-3-firmware#209]
* [x] include piv-authenticator for alpha releases https://github.com/Nitrokey/nitrokey-3-firmware/pull/233
* [x] provide storage option to set data persistance to external memory https://github.com/Nitrokey/piv-authenticator/pull/8

**Comment by sosthene-nitrokey** [comment]
Additionnal steps:

- [ ] Add rsa-backend (I think we should also merge the migration for opcard once we do that)
- [ ] Increase the size of trussed files https://github.com/trussed-dev/trussed/pull/78, so that we can support certificate that are large enough to be actually useful
