### ISSUE TITLE
Allow apps to delay/sleep

### ISSUE THREAD

**Issue by daringer** [Nitrokey/nitrokey-3-firmware#216]
That's likely not too easy to accomplish.
* We cannot really pass delay down to the client
* Busy wait using the monotonic timer is also likely not feasible
* Should there be an API call: `WaitFor` ?

This is currently needed by the `secrets-app` to rate-limit the reverse-hotp answers.

**Comment by sosthene-nitrokey** [comment]
Having a "sleep" syscall would mean also blocking all other apps from making any form of progress since they run in the same task. Maybe just have a way to get the time, and then the app can keep the time of the latest attempt, compare it to the current time, and if the difference is below a threshold reject the request?

**Comment by szszszsz** [comment]
> Maybe just have a way to get the time, and then the app can keep the time of the latest attempt, compare it to the current time, and if the difference is below a threshold reject the request?

1. This would work for my use case.
2. It sounds weird that RTIC does not support yielding. Are you sure?

**Comment by sosthene-nitrokey** [comment]
By nature of being a priority based real-time scheduler, RTIC does not have a way to yield and then resume a task outside of starting another higher-priority task, or completing the task and restarting it from the beginning. That's why V2 wants async, so that you can have that type of yielding.

**Comment by robin-nitrokey** [comment]
There already is [`ManagementClient::uptime`](https://docs.rs/trussed/latest/trussed/client/trait.ManagementClient.html#method.uptime).

**Comment by daringer** [comment]
Ok ok, perfectly fine. 
So then close this issue and anyone who would like to wait should do a busy-wait based on [ManagementClient::uptime](https://docs.rs/trussed/latest/trussed/client/trait.ManagementClient.html#method.uptime) ?

**Comment by daringer** [comment]
Closing this as there is nothing to be done inside the firmware, a client/app should use `uptime` to realize time dependent reactions
