### ISSUE TITLE
Misssing OpenPGP support in v1.3.1?

### ISSUE THREAD

**Issue by comio** [Nitrokey/nitrokey-3-firmware#227]
Hi Nitrokey Team,

I just upgraded to v1.3.1 firmware my NK3 Nano. The gpg/openpgp card support stopped to work.

```
gpg --card-status 
gpg: selecting card failed: Nessun device corrisponde
gpg: Scheda OpenPGP non disponibile: Nessun device corrisponde

```
I tried to reset via opensc-tool also.

Is the OpenPGP Card support missing in v1.3.1?

Thanks a lot.

ciao

luigi

**Comment by Chimrod** [comment]
Hello I have the same issue with a batch comming from the pre-order:

```
$ nitropy nk3 status
Command line tool to interact with Nitrokey devices 0.4.36
UUID:               B9EF61DC738B0E569C389B06AA249067
Firmware version:   v1.3.1
Init status:        ok
Free blocks (int):  60
Free blocks (ext):  478

$ gpg --card-status 
gpg: selecting card failed: No such device
gpg: OpenPGP card not available: No such device
```

**Comment by sosthene-nitrokey** [comment]
Hi,

OpenPGP support is not stable yet, and is therefore only available in the alpha firmware releases. We will soon release a 1.3.1 alpha version so that you can get OpenPGP functionality back.

**Comment by comio** [comment]
@sosthene-nitrokey 

I noticed the missing support. Can you upgrade the release page with a banner with this missing?
Thanks
luigi

**Comment by robin-nitrokey** [comment]
I’ve added it to the known issues.

**Comment by robin-nitrokey** [comment]
@comio [v1.3.1-test.20230417](https://github.com/Nitrokey/nitrokey-3-firmware/releases/tag/v1.3.1-test.20230417) with OpenPGP support is now available.
