### ISSUE TITLE
Change "Alpha" release name to "Test"

### ISSUE THREAD

**Issue by daringer** [Nitrokey/nitrokey-3-firmware#230]
- [x] use in new releases
- [ ] rename runner and apps feature
- [x] adapt CI
  - https://github.com/Nitrokey/nitrokey-3-firmware/pull/238
- [x] create user documentation
  - https://github.com/Nitrokey/nitrokey-documentation/pull/146

**Comment by szszszsz** [comment]
| Old | New |
| ---- | ---- |
| Alpha | Test |
