### ISSUE TITLE
fido-authenticator: Add self-diagnosis command

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/nitrokey-3-firmware#26]
The admin-app could have a command that checks whether the FIDO2 and Trussed certificates and keys are present and can be used successfully.

**Comment by robin-nitrokey** [comment]
We cannot have that command in the admin application because it cannot access the keys and certificates for the fido-authenticator application, but we could have it as a vendor command in the fido-authenticator itself (at least for the FIDO2 certificates and keys).

**Comment by szszszsz** [comment]
@robin-nitrokey 
I think we have decided on skipping this. Please reopen otherwise.
