### ISSUE TITLE
Add support for multiple certificate sets.

### ISSUE THREAD

**Issue by tuxmaster5000** [Nitrokey/nitrokey-3-firmware#287]
Until now, only one set  ( 2 keys  encryption/sing) can be stored on the device.
But for example using it for Thunderbird with multiple accounts it will not be enough.
I think the minimum capacity must be 4  - 6 sets (8  - 12 key pairs) for an real works usage.

**Comment by daringer** [comment]
Yes, generally we are planning to have multiple identities available for the OpenPGPCard functionality. Although I cannot give an ETA for that feature currently.

**Comment by camlafit** [comment]
Hello

Do you have any progress about this request ? Could be nice indeed :)

Thanks a lot
