### ISSUE TITLE
Delete OTP entries without button press or pin entry

### ISSUE THREAD

**Issue by peterwilli** [Nitrokey/nitrokey-3-firmware#303]
Device: NitroKey 3A Mini
Nitropy status:

```
Command line tool to interact with Nitrokey devices 0.4.38
UUID:               840E500EB2CFB1110000000000000000
Firmware version:   v1.5.0
Init status:        ok
Free blocks (int):  238
Free blocks (ext):  456
Variant:            NRF52
```

When running `nitropy nk3 secrets remove Discord`, tells me "Please touch the device if it blinks", but immediately shows "Done", and the key is gone.

Remarkably, when I run `nitropy nk3 secrets remove Discord` again, it will ask my pin number. Upon entering a valid pin, it asks me again to touch the device if it blinks. If I do this, I get:

```
peter@apx_managed_aur_dev:~$ nitropy nk3 secrets remove Discord
Command line tool to interact with Nitrokey devices 0.4.38
Please touch the device if it blinks
Credential not found. Please provide PIN below to search in the PIN-protected database.
Current PIN (8 attempts left): 
Please touch the device if it blinks
Critical error:
An unhandled exception occurred
	Exception encountered: SecretsAppException(code=6a82/NotFound)

--------------------------------------------------------------------------------
Critical error occurred, exiting now
Unexpected? Is this a bug? Would you like to get support/help?
- You can report issues at: https://support.nitrokey.com/
- Writing an e-mail to support@nitrokey.com is also possible
- Please attach the log: '/tmp/nitropy.log.0xd5z6n4' with any support/help request!
- Please check if you have udev rules installed: https://docs.nitrokey.com/nitrokey3/linux/firmware-update.html#troubleshooting
```

Ofcourse, the error above is expected, since the key is now gone from the chips database. Still, it is odd behaviour.
I reckon this is because my key wasn't added with `--protect-with-pin`, but it's strange that it asks me to touch the device yet immediately shoots to saying "Done" and deleting the key in question.

**Comment by szszszsz** [comment]
Hi! Thank you for the report!
This indeed seems to be a bug. Each modification of the state should be confirmed by a user touch. I will check it further.
