### ISSUE TITLE
Provide dashboard / overview of what is provided as a feature at present

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nitrokey-3-firmware#333]
I get confused about what features are provided or not at present. For example, if I understand correctly, the secret key is so far contained in the MCU, not the secure element? Or is the most recent firmware fully leveraging the secure element? This kind of information is quite critical, and important for me to decide when to transition from the Nitrokey Pro 2 to the Nitrokey 3.

Would it be possible to add a dashboard / overview, either ideally on the readme of this repo, or else somewhere easy to find in the documentation, to track this kind of questions (and other similar questions that may arise)?

**Comment by jerabaul29** [comment]
The idea would be to be able as a user, just taking a quick look, to decide if "we are NK3 ready yet" :) .

**Comment by robin-nitrokey** [comment]
With 1.7.0, you can choose whether the software implementation or the secure element is used.  The secure element is the default, but if you used GPG before with your device, it stays in software mode until you change that.  There will be a blog post that explains this in detail soon.

If the secure element is selected, the private keys are stored on it and all relevant cryptography operations are performed by the secure element.

**Comment by robin-nitrokey** [comment]
Yes, adding SE050 support for FIDO2 over USB would be possible in the future.  But it is not yet decided if and when it will be implemented.

**Comment by robin-nitrokey** [comment]
We now have a [Features](https://docs.nitrokey.com/nitrokey3/features) page in the Nitrokey 3 documentation that lists the available applications and whether they use the secure element.
