### ISSUE TITLE
authenticatorGetInfo falsely reports to support credMgmt

### ISSUE THREAD

**Issue by msirringhaus** [Nitrokey/nitrokey-3-firmware#334]
Using GetInfo, NK3 returns:
```
credMgmt: Some(true),
credentialMgmtPreview: Some(true),
```
while actually it only supports `credentialMgmtPreview` (as is expected of `FIDO_2_1_PRE`-devices).
`credMgmt` has the additional operation `updateUserInformation`, which NK3 doesn't understand yet.

**Comment by robin-nitrokey** [comment]
This should be fixed in [v1.7.0-rc.1](https://github.com/Nitrokey/nitrokey-3-firmware/releases/tag/v1.7.0-rc.1) as we now implement the `updateUserInformation` command.
