### ISSUE TITLE
Cannot remove RK using Chrome

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-3-firmware#38]
As a user I cannot remove RK using the Chrome interface for managing FIDO2 Security Key (non-Windows OS only).
Firmware version: v1.0.1, v1.0.2 (market samples).
Reproduction:
1. Create RK, e.g. using OpenSSH
2. Try to remove it using Chrome
3. See error:
> Security key sign-in data. Your sign-in data couldn't be deleted

**Comment by robin-nitrokey** [comment]
Cannot reproduce with v1.1.0.  @szszszsz Can you please try again with the current firmware?

**Comment by daringer** [comment]
Cannot reproduce with 1.3RC1, too. 

Should we close this ?
