### ISSUE TITLE
What is the difference with Solo key 2?

### ISSUE THREAD

**Issue by jerabaul29** [Nitrokey/nitrokey-3-firmware#39]
What is the difference between the Nitrokey 3 and the Solo key 2? In terms of both software and hardware? What should decide me to use one rather than the other? (I already have a couple of Nitrokey Pro 2, Nitrokey FIDO, and a Nitrokey Nextbox, so I am very positive to Nitrokey, but want to understand what the value proposition is with the NK3).

**Comment by szszszsz** [comment]
Closing as done. Let's continue on our [support.nitrokey.com](https://support.nitrokey.com/)  with related questions.

**Comment by jerabaul29** [comment]
Sounds excellent :) . My 2 cents: you may want to make this clear on the GH repos too, so that devs do not get confused :) .
