### ISSUE TITLE
fido-authenticator: Support downloading resident keys

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/nitrokey-3-firmware#48]
Upstream issue: https://github.com/solokeys/fido-authenticator/issues/10

Reported to work on NK3AM (NRF52) with openssh 9.0p1-1, libfido2 1.11.0-1 by @daringer.  We should check again after #46 is merged.

**Comment by szszszsz** [comment]
Good idea:
- Client: OpenSSH_8.7p1, OpenSSL 1.1.1o  FIPS 3 May 2022
- Server: OpenSSH_9.0p1 Debian-1+b1, OpenSSL 3.0.4 21 Jun 2022
