### ISSUE TITLE
Provide a caching option for OpenPGP UIF validity

### ISSUE THREAD

**Issue by farblos** [Nitrokey/nitrokey-3-firmware#493]
One of these other-smartcard-features, described, for example, [here](https://peterbabic.dev/blog/gnupg-pin-cache-smartcards-yubikeys-and-notifications#signing-with-yubikey-and-touch):

For `git rebase`s it would be helpful if the validity of a UIF touch event for the OpenPGP smartcard would be valid for at least a few seconds, so that not every single commit needed confirmation.

**Comment by robin-nitrokey** [comment]
See also: https://github.com/Nitrokey/opcard-rs/issues/106

**Comment by farblos** [comment]
Thanks for the pointer, I wasn't aware of that other repo/issue.  I have subscribed to the other issue, so feel free to close this one ...
