### ISSUE TITLE
Invalid test certificate

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-3-firmware#50]
While testing against fido2-tests I got multiple errors claiming the attestation certificate is invalid. To check and retest.

- Nitrokey 3 CN, LPC55, v1.0.3-24-ge0b4461, with no-reset-time-window.
- ` fido2.attestation.InvalidData: Attestation certificate must have CA=false!`
- https://github.com/solokeys/fido2-tests/commit/591d3d2279949e08de0766897f24bcfd39af1339

**Comment by robin-nitrokey** [comment]
Which certificate did you use?

**Comment by szszszsz** [comment]
Works with the updated certificate. Leaving this open to remind about pushing the current development certificates to this repository.

**Comment by szszszsz** [comment]
@daringer @robin-nitrokey were the new test certs updated/uploaded? Please close if so.

**Comment by robin-nitrokey** [comment]
Not yet.

**Comment by robin-nitrokey** [comment]
The certificates are now available at https://github.com/Nitrokey/nitrokey-3-firmware/tree/main/utils/test-certificates.
