### ISSUE TITLE
NK3AM: LED should blink when prompting for the user input

### ISSUE THREAD

**Issue by sosthene-nitrokey** [Nitrokey/nitrokey-3-firmware#93]
The NK3A NFC blinks when waiting for user input but the NK3AM shines. It should blink when it is waiting for user input.

**Comment by robin-nitrokey** [comment]
Which firmware version did you test this with?  Looking at the code, it should have been ported from lpc55 to nrf52 but maybe @daringer knows more.

**Comment by sosthene-nitrokey** [comment]
v1.2.2-alpha.opcard.0.1.0 and firmware-nk3am-nrf52-v1.2.2

**Comment by daringer** [comment]
While cleaning/fixing the LED blinking also remove this line, as it is redundant:

https://github.com/Nitrokey/nitrokey-3-firmware/blob/102f2eb34fadf01913c6cf2053a4c747e599eee3/runners/embedded/src/soc_nrf52840/trussed_ui.rs#L99
